version: 2
jobs:
  build:
    docker:
      - image: crystallang/crystal
      - image: redis:alpine
      - image: appcelerator/etcd
        command:
          - --listen-client-urls=http://localhost:2379
          - --advertise-client-urls=http://localhost:2379
          - --enable-v2=true
    environment:
      DOCS_PATH: "docs"
      GIT_USER: "icyleaf"
      GIT_EMAIL: "icyleaf.cn@gmail.com"
      GIT_REPO: "git@github.com:icyleaf/totem.git"
      GH_REF: "https://github.com/icyleaf/totem"
    branches:
      ignore:
        - gh-pages
    working_directory: ~/totem
    steps:
      - checkout
      - run:
          name: "Crystal version"
          command: crystal version
      - run:
          name: "Install dependencies"
          command: shards install --ignore-crystal-version
      - run:
          name: "Run code format check"
          command: |
            if ! crystal tool format --check; then
              crystal tool format
              git diff
              exit 1
            fi
      - run:
          name: "Specs"
          command: crystal spec