name: Deploy API documents
on:
  push:
    paths-ignore:
      - ".circleci/**"
    branches:
      - "master"
    tags:
      - "v*"

env:
  DOCS_PATH: docs
  GH_REF: https://github.com/icyleaf/totem
  GH_URL: https://icyleaf.github.io/totem

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        # fetch all tags and branches
        fetch-depth: 0
    - uses: oprypin/install-crystal@v1
    - name: Generate
      id: generate
      run: |
        shards install
        crystal docs --output="${DOCS_PATH}" --project-version="${{ github.ref }}"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.DOCS_PATH }}


